# Copyright (C) 2004, 2005, 2010 Valery Reznic
# This file is part of the Elf Statifier project
# 
# This project is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License.
# See LICENSE file in the doc directory.

PACKAGE := statifier
VERSION := $(shell cat $(TOP_DIR)/VERSION)
RELEASE := $(shell cat $(TOP_DIR)/RELEASE)

SUPPORTED_CPU_LIST := i386 x86_64

include $(TOP_DIR)/Makefile.include
